coredhcp_server_id: '{{ cluster_boot_ip }}'
coredhcp_dns_server: '{{ cluster_boot_ip }}'
coredhcp_router: '{{ cluster_boot_ip }}'
coredhcp_netmask: '255.255.255.0'
coredhcp_dhcp_pool: '172.16.0.200 172.16.0.250'
coredhcp_tmp_lease_duration: '5m'
coredhcp_lease_duration: '1h'
coredhcp_cache_validity: '30s'
