---
apiVersion: batch/v1
kind: Job
metadata:
  name: hydra-migrate
  namespace: {{ .Release.Namespace }}
spec:
  template:
    spec:
      containers:
      - name: hydra-migrate
        image: {{ .Values.hydra.deployment.image.repository }}/{{ .Values.hydra.deployment.image.name }}:{{ .Values.hydra.deployment.image.tag }}
        imagePullPolicy: {{ .Values.hydra.deployment.image.pullPolicy }}
        command: ["hydra"]
        args: ["migrate", "-c", "/etc/config/hydra/hydra.yml", "sql", "-e", "--yes"]
        volumeMounts:
        - name: hydra-config
          mountPath: /etc/config/hydra
          readOnly: true
        env:
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-pg-hydra
              key: password
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-pg-hydra
              key: username
        - name: PG_DB
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-pg-hydra
              key: database
        - name: PG_PORT
          value: "{{ .Values.postgresql.service.ports.postgresql }}"
        - name: DSN
          value: postgres://$(PG_USERNAME):$(PG_PASSWORD)@{{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local:$(PG_PORT)/$(PG_DB)?sslmode=disable&max_conns=20&max_idle_conns=4
        resources:
          requests:
            cpu: "50m"
      volumes:
      - name: hydra-config
        configMap:
          name: hydra-config
      restartPolicy: OnFailure
  backoffLimit: 4
