services:
  configurator:
    image: ghcr.io/openchami/configurator:latest
    container_name: configurator
    hostname: configurator
    command:
      - '/configurator/configurator'
      - 'serve'
      - '--config'
      - '/configurator/config.yaml'
      - '--verbose'
    volumes:
      - ./configs/configurator.yaml:/configurator/config.yaml
    networks:
      - internal
    ports:
      - 3334:3334
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:3334/configurator/status"]
      interval: 5s
      timeout: 10s
      retries: 60
